name: carbon_footprint
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - ipython
  - jupyter
  - jupyterlab
  - numpy
  - scipy
  - matplotlib
  - conda-forge::astropy>=2
  - pip:
    - version_information
